[tools]
zig = "0.15.2"
bun = "latest"
shellcheck = "latest"
cosign = "3.0.5"
"github:indygreg/apple-platform-rs" = { version = "apple-codesign/0.29.0", exe = "rcodesign", matching = "apple-codesign" }
