[project]
name = "whisper"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "librosa",
    "torchaudio",
    "torch",
    "tqdm",
    "tiktoken",
    "triton>=2.0.0; platform_machine == 'x86_64' and (sys_platform == 'linux' or sys_platform == 'linux2')",
]

[tool.uv]
find-links = ["SimulStreaming"]
